services:
  # --- MySQL Master
  mysql_master:
    image: mysql:8.0
    container_name: mysql_master
    ports:
      - "3307:3306"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
    volumes:
      - ./init/master:/docker-entrypoint-initdb.d
      - ./init/master/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "--password=root_password"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # --- MySQL Slave
  mysql_slave:
    image: mysql:8.0
    container_name: mysql_slave
    ports:
      - "3308:3306"
    networks:
      - backend
    depends_on:
      - mysql_master
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
    volumes:
      - ./init/slave:/docker-entrypoint-initdb.d
      - ./init/slave/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "--password=root_password"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
  # --- Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    ports:
      - "8080:80"
    depends_on:
      - angular_app1
      - angular_app2
      - spring_app1
      - spring_app2
    networks:
      - frontend
      - backend

  # --- Application Angular (2 instances)
  angular_app1:
    build:
      context: ./angular-app
    container_name: angular_app1
    ports:
      - "4201:80"
    networks:
      - frontend

  angular_app2:
    build:
      context: ./angular-app
    container_name: angular_app2
    ports:
      - "4202:80"
    networks:
      - frontend

  # --- Application Spring Boot (2 instances)
  spring_app1:
    build:
      context: ./spring-app
    container_name: spring_app1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_master:3306/mydb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root_password
    depends_on:
      - mysql_master
    ports:
      - "8083:8080"
    networks:
      - backend
    command: >
      sh -c "until mysqladmin ping -h mysql_master -u root --password=root_password --silent; do echo 'Waiting for MySQL Master'; sleep 5; done && java -jar app.jar"

  spring_app2:
    build:
      context: ./spring-app
    container_name: spring_app2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_slave:3306/mydb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root_password
    depends_on:
      - mysql_slave
    ports:
      - "8084:8080"
    networks:
      - backend
    command: >
      sh -c "until mysqladmin ping -h mysql_slave -u root --password=root_password --silent; do echo 'Waiting for MySQL Slave'; sleep 5; done && java -jar app.jar"

  # --- ELK
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - backend

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.13
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./nginx/logs:/var/log/nginx
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx256m"
    ports:
      - "5044:5044"
      - "5000:5000"
    networks:
      - backend

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.13
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - backend
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

volumes:
  es_data:
  mysql_slave_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
