version: "3.8"

services:
  # --- Load Balancer (Nginx)
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    ports:
      - "8080:80"
    depends_on:
      - angular_app1
      - angular_app2
      - spring_app1
      - spring_app2
    networks:
      - frontend
      - backend

  # --- Application Angular (2 instances)
  angular_app1:
    build:
      context: ./angular-app
    container_name: angular_app1
    ports:
      - "4201:80"
    networks:
      - frontend

  angular_app2:
    build:
      context: ./angular-app
    container_name: angular_app2
    ports:
      - "4202:80"
    networks:
      - frontend

  # --- Application Spring Boot (2 instances)
  spring_app1:
    build:
      context: ./spring-app
    container_name: spring_app1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_master:3306/mydb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root_password
    depends_on:
      - mysql_master
    ports:
      - "8083:8080"
    networks:
      - backend

  spring_app2:
    build:
      context: ./spring-app
    container_name: spring_app2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_slave:3306/mydb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root_password
    depends_on:
      - mysql_slave
    ports:
      - "8084:8080"
    networks:
      - backend

  # --- MySQL Master
  mysql_master:
    image: mysql:8.0
    container_name: mysql_master
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=mydb
    volumes:
      - mysql_master_data:/var/lib/mysql
      - ./init-scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "3307:3306"
    networks:
      - backend

  # --- MySQL Slave
  mysql_slave:
    image: mysql:8.0
    container_name: mysql_slave
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=mydb
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_MASTER_HOST=mysql_master
      - MYSQL_MASTER_USER=replicator
      - MYSQL_MASTER_PASSWORD=replicator_password
    volumes:
      - mysql_slave_data:/var/lib/mysql
    depends_on:
      - mysql_master
    ports:
      - "3308:3306"
    networks:
      - backend

  # --- Elasticsearch
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
#    container_name: elasticsearch
#    environment:
#      - discovery.type=single-node
#      - ES_JAVA_OPTS=-Xms512m -Xmx512m
#    volumes:
#      - elasticsearch_data:/usr/share/elasticsearch/data
#    ports:
#      - "9200:9200"
#    networks:
#      - backend
      

  # --- Logstash
#  logstash:
#    image: docker.elastic.co/logstash/logstash:8.10.2
#    container_name: logstash
#    volumes:
#      - ./elk-stack/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#    ports:
#      - "5044:5044"
#    networks:
#      - backend
#    depends_on:
#      - elasticsearch  # Pour être sûr que Logstash démarre après Elasticsearch

volumes:
  mysql_master_data:
  mysql_slave_data:
  elasticsearch_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

