input {

  file {
    path => "/var/log/nginx/*.log"     # Chemin monté en volume
    start_position => "beginning"
    sincedb_path => "/dev/null"        # Évite de marquer la position. Utile pour tests
  }
  

}

filter {
  # On peut utiliser un grok filter pour parser les logs NGINX
  grok {
    match => { "message" => "%{COMBINEDAPACHELOG}" }
  }
  
  # Ajout de champs, suppression, etc.
  date {
    match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
    remove_field => [ "timestamp" ]
  }
}

output {
  # Envoi vers Elasticsearch
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "nginx-logs-%{+YYYY.MM.dd}"
  }
  
  # Debug en console (pour tester)
  stdout {
    codec => rubydebug
  }
}

