events {}

http {
    upstream angular_pool {
        server angular_app1:80;
        server angular_app2:80;
    }

    upstream spring_pool {
        server spring_app1:8080;
        server spring_app2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://angular_pool;
        }

        location /api/ {
            proxy_pass http://spring_pool;
        }
    }
}
