# Section globale, avant les upstreams et serveur
events {
    worker_connections 1024;  # Nombre maximal de connexions par worker
}

http {
    upstream angular_apps {
        server angular_app1:80;  # Nom du conteneur Docker pour Angular app 1
        server angular_app2:80;  # Nom du conteneur Docker pour Angular app 2
    }

    upstream spring_apps {
        server spring_app1:8080;  # Nom du conteneur Docker pour Spring app 1
        server spring_app2:8080;  # Nom du conteneur Docker pour Spring app 2
    }

    server {
        listen 80;

        # Gestion des requêtes vers Angular
        location / {
            proxy_pass http://angular_apps;  # Envoie vers une des deux apps Angular
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Gestion des requêtes vers Spring API
        location /api/ {
            proxy_pass http://spring_apps;  # Envoie vers une des deux apps Spring
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}


